-- Momentum V4: incolla tutto questo nel Supabase SQL Editor
create table if not exists public.daily_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, date)
);

alter table public.daily_entries enable row level security;

drop policy if exists "Users can read own days" on public.daily_entries;
create policy "Users can read own days" on public.daily_entries
for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can insert own days" on public.daily_entries;
create policy "Users can insert own days" on public.daily_entries
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can update own days" on public.daily_entries;
create policy "Users can update own days" on public.daily_entries
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can delete own days" on public.daily_entries;
create policy "Users can delete own days" on public.daily_entries
for delete to authenticated using (auth.uid() = user_id);
